import Foundation

/// ADIF 3.1.4 export on `ContestDefinition`. Each logged row (including each
/// county-line row) becomes one ADIF record; the shared group id rides along
/// in an APP_ field so other tools can reassociate county-line pairs. Fields
/// follow the exchange elements by kind: `rst` → `rst_sent`/`rst_rcvd`,
/// `serial` → `stx`/`srx`, `name` → `my_name`/`name`, `memberOrPower` → the
/// APP_ member fields, the `location` token → `stx_string`/`srx_string` (and
/// `cnty`/`state` where it names a county or state), `section` → `arrl_sect`,
/// `cqZone` → `cqz`, `ituZone` → `ituz`, `precedence`/`check`/`classToken`
/// → their ADIF names, `grid` → `gridsquare`, a numeric `power` → `tx_pwr` /
/// `rx_pwr`; `dxcc`/`cont` from cty where the contest resolves the worked
/// call's entity or zone. Every party's ADIF is byte-identical to before.
enum AdifExporter {

    static func export(log: ContestLog, contest: ContestDefinition) -> String {
        var out = "Generated by QSO Party Logger — \(contest.name)\n"
        out += field("adif_ver", "3.1.4")
        out += field("programid", "QSOPartyLogger")
        out += "<eoh>\n\n"

        let side = contest.resolvedSideID(log.sideID)
        let myCall = log.station.callsign.uppercased()
        let counties = contest.countyRoster()
        let myState = adifState(for: log, contest: contest, side: side)
        // The worked call's entity and continent are written where the contest
        // reads them — a country class from the callsign, or a zone element.
        let writesEntity = contest.multipliers.contains { $0.resolvers.contains { $0.kind == .dxccEntity && $0.from == .callsign } }
            || contest.exchange.contains { $0.kind == .cqZone || $0.kind == .ituZone }

        for q in log.qsos.sortedChronologically() {
            out += record(q, myCall: myCall, contest: contest, side: side, counties: counties, myState: myState, writesEntity: writesEntity)
        }
        return out
    }

    /// The `PartyDefinition` overload: lower, then export on the model.
    static func export(log: ContestLog, party: PartyDefinition) -> String {
        export(log: log, contest: PartyLowering.lowered(party))
    }

    /// The entrant's own state for `my_state`: a first-listed-side entrant's
    /// `homeLocation` (a party's own state, including the province codes the
    /// Canadian parties use); otherwise the sent location token only when it
    /// really is a US state, so an NAQP entrant in Mexico leaves the field
    /// empty rather than claiming `XE` is a state; otherwise
    /// `exchangeDefaults["state"]` when that is one.
    private static func adifState(for log: ContestLog, contest: ContestDefinition, side: String) -> String {
        if contest.cabrillo.location == .state, let home = contest.cabrillo.homeLocation, side == contest.sides.first?.id { return home }
        let token = (log.sentExchange[ExchangeElementID.location]?.first ?? log.station.exchangeDefaults["state"] ?? "").uppercased()
        return TokenSet.usStates.abbrs.contains(token) ? token : ""
    }

    private static let dateF: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd"
        f.timeZone = TimeZone(identifier: "UTC")
        f.locale = Locale(identifier: "en_US_POSIX")
        return f
    }()

    private static let timeF: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HHmmss"
        f.timeZone = TimeZone(identifier: "UTC")
        f.locale = Locale(identifier: "en_US_POSIX")
        return f
    }()

    static func field(_ name: String, _ value: String) -> String {
        value.isEmpty ? "" : "<\(name):\(value.utf8.count)>\(value) "
    }

    static func record(_ q: QSO, myCall: String, contest: ContestDefinition, side: String,
                       counties: TokenSet?, myState: String, writesEntity: Bool) -> String {
        var r = ""
        r += field("qso_date", dateF.string(from: q.timestampUTC))
        r += field("time_on", timeF.string(from: q.timestampUTC))
        r += field("call", q.call.uppercased())
        r += field("band", q.band.adif)
        if let kHz = q.freqKHz {
            r += field("freq", String(format: "%.6f", Double(kHz) / 1000.0))
        }
        r += field("mode", adifMode(q.rawMode))
        r += field("rst_sent", q.rstSent)
        r += field("rst_rcvd", q.rstRcvd)
        // ADIF 3.1.4 keeps serials separate from reports: STX/SRX are the
        // transmitted/received serial numbers.
        if let stx = q.serialSent { r += field("stx", String(stx)) }
        if let srx = q.serialRcvd { r += field("srx", String(srx)) }
        r += field("my_name", (q.nameSent ?? "").uppercased())
        r += field("name", (q.nameRcvd ?? "").uppercased())
        // The member-number-or-power element (Skeeter Hunt). ADIF 3.1.4 has
        // no field for a club number, and stx_string/srx_string are already
        // the locations, so it rides APP_ fields.
        r += field("app_qsopartylogger_member_sent", (q.memberSent ?? "").uppercased())
        r += field("app_qsopartylogger_member_rcvd", (q.memberRcvd ?? "").uppercased())
        r += field("stx_string", q.myLoc.uppercased())
        r += field("srx_string", q.theirLoc.uppercased())
        r += field("contest_id", contest.cabrillo.contest)

        // The location token: a county names its state and county, a bare
        // state token names the state.
        let theirLoc = q.theirLoc.uppercased()
        if let county = counties?.token(for: theirLoc), let state = county.group, let name = county.name {
            r += field("cnty", "\(state),\(name)")
            r += field("state", state)
        } else if TokenSet.usStates.abbrs.contains(theirLoc) {
            r += field("state", theirLoc)
        }
        let myLoc = q.myLoc.uppercased()
        if let county = counties?.token(for: myLoc), let state = county.group, let name = county.name {
            r += field("my_cnty", "\(state),\(name)")
            r += field("my_state", state)
        } else if !myState.isEmpty {
            r += field("my_state", myState)
        }

        // The general contests' elements, by kind.
        for element in contest.exchange where element.kind != .token && element.kind != .rst
            && element.kind != .serial && element.kind != .name && element.kind != .memberOrPower && element.kind != .callEcho {
            let sent = (q.sent[element.id] ?? "").uppercased(), rcvd = (q.rcvd[element.id] ?? "").uppercased()
            switch element.kind {
            case .cqZone: r += field("my_cq_zone", sent); r += field("cqz", rcvd)
            case .ituZone: r += field("my_itu_zone", sent); r += field("ituz", rcvd)
            case .precedence: r += field("precedence", rcvd)
            case .check: r += field("check", rcvd)
            case .classToken: r += field("class", rcvd)
            case .grid: r += field("my_gridsquare", sent); r += field("gridsquare", rcvd)
            case .power:
                if !sent.isEmpty, sent.allSatisfy(\.isNumber) { r += field("tx_pwr", sent) }
                if !rcvd.isEmpty, rcvd.allSatisfy(\.isNumber) { r += field("rx_pwr", rcvd) }
            case .report:
                // A digital report stands in for the RST where the contest has no rst element.
                if !contest.exchange.contains(where: { $0.kind == .rst }) { r += field("rst_rcvd", rcvd) }
            default: break
            }
        }
        // A section token element (Sweepstakes, Field Day): the ARRL section
        // fields — a party's `location` never comes here (its kind is token
        // and its id is `location`).
        for element in contest.exchange where element.kind == .token && element.id == "section" {
            r += field("my_arrl_sect", (q.sent[element.id] ?? "").uppercased())
            r += field("arrl_sect", (q.rcvd[element.id] ?? "").uppercased())
        }
        if writesEntity, let m = CTYTable.shared?.match(callsign: q.call), let code = m.entity.entityCode {
            r += field("dxcc", String(code))
            r += field("cont", m.continent)
        }

        // POTA: one emitted record per (my park × their park) pair — POTA's
        // uploader reads a single park per record from MY_SIG_INFO / SIG_INFO
        // (docs/research/pota/SOURCES.md). A row with no parks takes each loop
        // once and emits zero new fields.
        let myParks: [String?] = (q.myPotaRefs?.isEmpty ?? true) ? [nil] : q.myPotaRefs!.map(Optional.some)
        let theirParks: [String?] = (q.theirPotaRefs?.isEmpty ?? true) ? [nil] : q.theirPotaRefs!.map(Optional.some)
        var records = ""
        for myPark in myParks {
            for theirPark in theirParks {
                var rec = r
                if let myPark {
                    rec += field("my_sig", "POTA")
                    rec += field("my_sig_info", myPark)
                    rec += field("my_pota_ref", myPark)
                }
                if let theirPark {
                    rec += field("sig", "POTA")
                    rec += field("sig_info", theirPark)
                    rec += field("pota_ref", theirPark)
                }
                rec += field("station_callsign", myCall)
                rec += field("operator", myCall)
                rec += field("app_qsopartylogger_groupid", q.groupID.uuidString)
                rec += "<eor>\n"
                records += rec
            }
        }
        return records
    }

    static func adifMode(_ rawMode: String) -> String {
        switch rawMode.uppercased() {
        case "USB", "LSB", "SSB": "SSB"
        default: rawMode.uppercased()
        }
    }
}
