import Foundation

/// ADIF 3.1.4 export. Each logged row (including each county-line row) becomes
/// one ADIF record; the shared group id rides along in an APP_ field so other
/// tools can reassociate county-line pairs.
enum AdifExporter {

    static func export(log: ContestLog, party: PartyDefinition) -> String {
        var out = "Generated by QSO Party Logger — \(party.name)\n"
        out += field("adif_ver", "3.1.4")
        out += field("programid", "QSOPartyLogger")
        out += "<eoh>\n\n"

        let myCall = log.station.callsign.uppercased()
        let countyNames = Dictionary(uniqueKeysWithValues: party.counties.map { ($0.abbr, $0.name) })
        let myState = adifState(for: log, party: party)

        for q in log.qsos.sortedChronologically() {
            out += record(
                q,
                myCall: myCall,
                party: party,
                countyNames: countyNames,
                myState: myState
            )
        }
        return out
    }

    private static func adifState(for log: ContestLog, party: PartyDefinition) -> String {
        switch log.myLocation {
        case .inState: party.homeState
        case .outOfState(let loc):
            MultClass.acceptedStateTokens.contains(loc.uppercased()) ? loc.uppercased() : ""
        }
    }

    private static let dateF: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd"
        f.timeZone = TimeZone(identifier: "UTC")
        f.locale = Locale(identifier: "en_US_POSIX")
        return f
    }()

    private static let timeF: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "HHmmss"
        f.timeZone = TimeZone(identifier: "UTC")
        f.locale = Locale(identifier: "en_US_POSIX")
        return f
    }()

    static func field(_ name: String, _ value: String) -> String {
        value.isEmpty ? "" : "<\(name):\(value.utf8.count)>\(value) "
    }

    static func record(
        _ q: QSO,
        myCall: String,
        party: PartyDefinition,
        countyNames: [String: String],
        myState: String
    ) -> String {
        var r = ""
        r += field("qso_date", dateF.string(from: q.timestampUTC))
        r += field("time_on", timeF.string(from: q.timestampUTC))
        r += field("call", q.call.uppercased())
        r += field("band", q.band.adif)
        if let kHz = q.freqKHz {
            r += field("freq", String(format: "%.6f", Double(kHz) / 1000.0))
        }
        r += field("mode", adifMode(q.rawMode))
        r += field("rst_sent", q.rstSent)
        r += field("rst_rcvd", q.rstRcvd)
        // ADIF 3.1.4 keeps serials separate from reports: STX/SRX are the
        // transmitted/received serial numbers. Written only where the party
        // exchanges one, so every other party's ADIF is byte-identical.
        if let stx = q.serialSent { r += field("stx", String(stx)) }
        if let srx = q.serialRcvd { r += field("srx", String(srx)) }
        r += field("stx_string", q.myLoc.uppercased())
        r += field("srx_string", q.theirLoc.uppercased())
        r += field("contest_id", party.cabrilloContest)

        let theirLoc = q.theirLoc.uppercased()
        if let countyName = countyNames[theirLoc] {
            let theirState = party.state(forCounty: theirLoc)
            r += field("cnty", "\(theirState),\(countyName)")
            r += field("state", theirState)
        } else if MultClass.acceptedStateTokens.contains(theirLoc) {
            r += field("state", theirLoc)
        }

        let myLoc = q.myLoc.uppercased()
        if let myCountyName = countyNames[myLoc] {
            let ownState = party.state(forCounty: myLoc)
            r += field("my_cnty", "\(ownState),\(myCountyName)")
            r += field("my_state", ownState)
        } else if !myState.isEmpty {
            r += field("my_state", myState)
        }

        r += field("station_callsign", myCall)
        r += field("operator", myCall)
        r += field("app_qsopartylogger_groupid", q.groupID.uuidString)
        r += "<eor>\n"
        return r
    }

    static func adifMode(_ rawMode: String) -> String {
        switch rawMode.uppercased() {
        case "USB", "LSB", "SSB": "SSB"
        default: rawMode.uppercased()
        }
    }
}
