import XCTest
@testable import QSOPartyLogger

/// The banked N1MM call history mapping. Every value was fetched from
/// n1mmwp.hamdocs.com on 2026-07-28 and verified against the files' own
/// `# QSOPARTY` declarations — regenerated by
/// `docs/research/gen_callhistory.py`, provenance in
/// `docs/research/n1mm_callhistory.md`.
final class CallHistorySourceTests: XCTestCase {

    // MARK: The bundled roster

    /// Alabama, the party the download mechanics were first proven against.
    func testAlabamaCarriesItsCallHistorySource() throws {
        let alqp = try XCTUnwrap(PartyCatalog.party(id: "alqp"))
        let source = try XCTUnwrap(alqp.callHistory)
        XCTAssertEqual(source.filePrefix, "QSOP_AL")
        XCTAssertEqual(source.token, "QSOPARTY AL")
    }

    /// 46 of the 49 bundled parties have a source upstream — 45 on the N1MM
    /// listing plus the Skeeter Hunt's sponsor roster page. A party joining
    /// or leaving this set changes what the app downloads, so it must be a
    /// deliberate edit backed by a regenerated mapping — never incidental.
    func testExactlyThreePartiesHaveNoCallHistoryFile() {
        let without = PartyCatalog.loadBundled()
            .filter { $0.callHistory == nil }
            .map(\.id)
            .sorted()
        XCTAssertEqual(without, ["azqp", "mdc", "vtqp"],
                       "no QSOP_AZ, QSOP_MD/MDC or QSOP_VT file exists in the "
                       + "504-file inventory of 2026-07-28")
        XCTAssertEqual(PartyCatalog.loadBundled().count - without.count, 46)
    }

    /// The one non-N1MM source: the Skeeter Hunt roster, discovered from the
    /// sponsor page because its sheet id changes every season.
    func testOnlyTheSkeeterHuntUsesARosterPage() {
        let rosters = PartyCatalog.loadBundled()
            .filter { $0.callHistory?.kind == .w2ljRosterPage }
            .map(\.id)
        XCTAssertEqual(rosters, ["skeeter"])
        for party in PartyCatalog.loadBundled()
        where party.callHistory?.kind == .n1mm {
            XCTAssertNil(party.callHistory?.pageURL,
                         "\(party.id): the N1MM kind carries no page URL")
        }
    }

    /// One file serves the whole shared May weekend — the sponsors' own
    /// maintainers merged them: "There will be only one file for all, in
    /// 2026". Five parties, one prefix, each verified by its own token.
    func testMayWeekendPartiesShareTheCombinedFile() throws {
        let expected: [String: String] = [
            "inqp": "QSOPARTY IN",
            "sevenqp": "QSOPARTY 7QP",
            "newenglandqp": "QSOPARTY NEWE",
            "deqp": "QSOPARTY DE",
            "in7qpne": "QSOPARTY IN7QPNE",
        ]
        for (id, token) in expected {
            let source = try XCTUnwrap(
                PartyCatalog.party(id: id)?.callHistory, id)
            XCTAssertEqual(source.filePrefix, "QSOP_IN7QPNE_DE", id)
            XCTAssertEqual(source.token, token, id)
        }
    }

    /// The NAQPs are N1MM contest modules, not QSOPARTY sub-states; their
    /// files carry the module name.
    func testNAQPsUseTheirModuleFiles() throws {
        let cw = try XCTUnwrap(PartyCatalog.party(id: "naqpcw")?.callHistory)
        XCTAssertEqual(cw.filePrefix, "NAQPCW")
        XCTAssertEqual(cw.token, "NAQPCW")
        let ssb = try XCTUnwrap(PartyCatalog.party(id: "naqpssb")?.callHistory)
        XCTAssertEqual(ssb.filePrefix, "NAQPSSB")
        XCTAssertEqual(ssb.token, "NAQPSSB")
    }

    // MARK: Filename claims

    private let nebraska = CallHistorySource(filePrefix: "QSOP_NE", token: "QSOPARTY NE")

    func testClaimsRevisionsUnderEverySeparator() {
        XCTAssertTrue(nebraska.claims(fileNamed: "QSOP_NE-2026-002.txt"))
        XCTAssertTrue(nebraska.claims(fileNamed: "QSOP_NE_2026.txt"),
                      "Florida's real file is QSOP_FL_2026-009.txt — underscore")
        XCTAssertTrue(nebraska.claims(fileNamed: "QSOP_NE.txt"),
                      "NAQPSSB.txt ships bare — the dot is a separator")
        XCTAssertTrue(nebraska.claims(fileNamed: "qsop_ne-2026.TXT"),
                      "case-insensitive both ways")
    }

    /// The trap the separator rule exists for: prefixes that are prefixes of
    /// other parties' prefixes.
    func testDoesNotClaimAnotherPartysLongerPrefix() {
        XCTAssertFalse(nebraska.claims(fileNamed: "QSOP_NEWE-2025.txt"),
                       "New England is not Nebraska")
        let indiana = CallHistorySource(filePrefix: "QSOP_IN", token: nil)
        XCTAssertFalse(indiana.claims(fileNamed: "QSOP_IN7QPNE_DE-2026-006.txt"),
                       "the combined file is claimed via its full prefix only")
        XCTAssertFalse(nebraska.claims(fileNamed: "QSOP_N-1.txt"))
        XCTAssertFalse(nebraska.claims(fileNamed: "QSOP_NE2026.txt"),
                       "no separator, no claim")
    }

    // MARK: Token declarations

    func testTokenMatchingIsWhitespaceBlind() {
        let ohio = CallHistorySource(filePrefix: "QSOP_OH", token: "QSOPARTY OH")
        XCTAssertTrue(
            ohio.isDeclared(inCommentTokens: [CallHistorySource.normalized("QSO PARTY OH")]),
            "QSOP_OH-2025-003.txt really writes '# QSO PARTY OH'")
        XCTAssertTrue(ohio.isDeclared(inCommentTokens: ["QSOPARTYOH"]))
        XCTAssertFalse(ohio.isDeclared(inCommentTokens: ["QSOPARTYOK", "OHIO"]))
    }

    func testMissingTokenSkipsTheCheck() {
        let userFile = CallHistorySource(filePrefix: "QSOP_XX", token: nil)
        XCTAssertTrue(userFile.isDeclared(inCommentTokens: []))
    }

    // MARK: Decoding

    func testDecodesWithAndWithoutToken() throws {
        let decoder = JSONDecoder()
        let full = try decoder.decode(
            CallHistorySource.self,
            from: Data(#"{"filePrefix": "QSOP_KS", "token": "QSOPARTY KS"}"#.utf8))
        XCTAssertEqual(full.filePrefix, "QSOP_KS")
        XCTAssertEqual(full.token, "QSOPARTY KS")
        let bare = try decoder.decode(
            CallHistorySource.self,
            from: Data(#"{"filePrefix": "QSOP_KS"}"#.utf8))
        XCTAssertNil(bare.token)
    }
}
