import XCTest
@testable import QSOPartyLogger

/// The banked qsopartyhub.com mapping. Every value here was fetched from the
/// live site on 2026-07-25 and is regenerated by `docs/research/gen_hub_map.py`
/// — see `docs/research/qsopartyhub.md` for provenance.
final class HubSpotSourceTests: XCTestCase {

    /// Alabama is the party this was verified against live, mid-contest.
    func testAlabamaCarriesItsHubSpotSource() throws {
        let alqp = try XCTUnwrap(PartyCatalog.party(id: "alqp"))
        let hub = try XCTUnwrap(alqp.hubSpots, "ALQP is served by the hub")
        XCTAssertEqual(hub.tableURL, "http://qsopartyhub.com/alqp-table.php")
        XCTAssertEqual(hub.postURL, "http://qsopartyhub.com/alqp-spots.php")
    }

    /// The hub serves 17 of the 19 bundled parties. A party joining or leaving
    /// this set changes where the app polls, so it must be a deliberate edit
    /// backed by a regenerated mapping — never incidental.
    func testExactlyThirtyFivePartiesAreServedByTheHub() {
        let served = PartyCatalog.loadBundled()
            .filter { $0.hubSpots != nil }
            .map(\.id)
            .sorted()
        XCTAssertEqual(
            served,
            ["alqp", "azqp", "bcqp", "coqp", "gaqp", "hqp", "iaqp", "idqp", "ilqp", "ksqp", "laqp", "mdc", "meqp", "miqp",
             "mnqp", "moqp", "msqp",
             "ncqp", "ndqp", "nhqp", "njqp", "nmqp", "nyqp", "ohqp", "okqp", "oqp", "paqp", "qcqp", "scqp", "sdqp", "tnqp", "tqp",
             "vaqp", "vtqp", "wiqp"]
        )
    }

    /// CQP is the trap that makes the URL prefix unusable as the source of
    /// truth: `caqp-table.php` returns a well-formed but permanently empty
    /// table, while the party's own page embeds `qp-table.php`, which
    /// 302-redirects. Guessing the prefix yields a poller that runs forever,
    /// never errors, and shows nothing.
    func testCaliforniaIsNotServedBecauseItsPageIsAStub() throws {
        let cqp = try XCTUnwrap(PartyCatalog.party(id: "cqp"))
        XCTAssertNil(cqp.hubSpots)
    }

    /// WA Salmon Run has no hub page at all — `waqp-spots.php` is a 404. The
    /// orphaned `waqp-table.php` shell must not tempt us into polling it.
    func testSalmonRunIsNotServed() throws {
        let warun = try XCTUnwrap(PartyCatalog.party(id: "warun"))
        XCTAssertNil(warun.hubSpots)
    }

    /// Three parties' hub pages do not use the party id.
    func testAliasedPrefixesResolveToTheHubsOwnNames() throws {
        let expected = [
            "mdc": "mdcqp",
            "tqp": "txqp",
            "hqp": "hiqp",
        ]
        for (partyID, hubPrefix) in expected {
            let party = try XCTUnwrap(PartyCatalog.party(id: partyID))
            let hub = try XCTUnwrap(party.hubSpots, "\(partyID) is served by the hub")
            XCTAssertEqual(hub.tableURL, "http://qsopartyhub.com/\(hubPrefix)-table.php")
        }
    }

    /// Illinois is the one county-token divergence: the hub spells Pulaski
    /// `PULS`, while the official ILQP abbreviation list (`ilqp_counties.txt`)
    /// spells it `PULA`. The app's value is correct, so the alias translates
    /// the hub's token inbound — and must translate back when self-spotting,
    /// since `PULS` is the only value the hub's own form accepts.
    func testIllinoisAliasesTheHubsPulaskiTypo() throws {
        let ilqp = try XCTUnwrap(PartyCatalog.party(id: "ilqp"))
        let hub = try XCTUnwrap(ilqp.hubSpots)
        XCTAssertEqual(hub.countyAliases["PULS"], "PULA")
    }

    /// Illinois is the *only* divergence. If a regenerated mapping introduces
    /// another, that is either a new hub typo or an error in our county list —
    /// both need a human to look, so the count is pinned.
    func testIllinoisIsTheOnlyPartyNeedingCountyAliases() {
        let withAliases = PartyCatalog.loadBundled()
            .filter { !($0.hubSpots?.countyAliases ?? [:]).isEmpty }
            .map(\.id)
        XCTAssertEqual(withAliases, ["ilqp"])
    }

    /// Every aliased token must resolve to a real county in that party, or the
    /// inbound translation would produce a multiplier the party does not have.
    func testEveryAliasTargetIsARealCountyInThatParty() {
        for party in PartyCatalog.loadBundled() {
            let abbrs = Set(party.counties.map(\.abbr))
            for (hubToken, appToken) in party.hubSpots?.countyAliases ?? [:] {
                XCTAssertTrue(
                    abbrs.contains(appToken),
                    "\(party.id): alias \(hubToken) -> \(appToken) targets a county that does not exist"
                )
                XCTAssertFalse(
                    abbrs.contains(hubToken),
                    "\(party.id): \(hubToken) is already a valid county — aliasing it would shadow a real multiplier"
                )
            }
        }
    }
}
