import XCTest
@testable import QSOPartyLogger

/// North American QSO Party, CW — built from NCJ's own 2026 rules document
/// and the official paper-log multiplier checklist, read verbatim 2026-07-27.
/// See docs/research/naqpcw_rules.md.
///
/// **Not a State QSO Party** — and the first bundled contest that is not:
/// no counties (the sponsor's 46-of-47 country list rides in the county
/// slot), no home state, no in/out asymmetry, a name in the exchange, and
/// deliberately **absent from the State QSO Party Challenge**.
@MainActor
final class NorthAmericanQSOPartyCWTests: XCTestCase {

    var naqp: PartyDefinition!

    override func setUpWithError() throws {
        naqp = try XCTUnwrap(PartyCatalog.party(id: "naqpcw"), "bundled NAQP CW should load")
    }

    var seq: TimeInterval = 0
    func qso(
        call: String = "N2CU", band: Band = .m20, mode: ModeClass = .cw,
        my: String = "TX", their: String = "NY",
        nameSent: String? = "TOM", nameRcvd: String? = "BILL"
    ) -> QSO {
        seq += 60
        // 2026-08-01 18:00Z + n minutes — inside the August window.
        return QSO(
            timestampUTC: Date(timeIntervalSince1970: 1_785_607_200 + seq),
            call: call, band: band, modeClass: mode,
            rawMode: mode == .phone ? "SSB" : mode == .cw ? "CW" : "RTTY",
            rstSent: "", rstRcvd: "",
            nameSent: nameSent, nameRcvd: nameRcvd,
            myLoc: my, theirLoc: their
        )
    }

    func log(_ qsos: [QSO]) -> ContestLog {
        var log = ContestLog(partyID: "naqpcw")
        log.myLocation = .outOfState(location: "TX")
        log.station.callsign = "KE5CW"
        log.station.name = "Tom"
        log.exchangeName = "TOM"
        log.qsos = qsos
        return log
    }

    // MARK: The country list

    /// The sponsor's checklist, generated by gen_naqp.py with names joined
    /// from the ARRL DXCC List (the authority rules 3 and 11 designate).
    /// Spot checks are the join's hard cases, not the easy ones.
    func testTheCountryListIsTheSponsorsChecklist() {
        XCTAssertEqual(naqp.counties.count, 46, "47 printed, HI shadowed by Hawaii")
        XCTAssertEqual(Set(naqp.counties.map(\.abbr)).count, 46)

        XCTAssertEqual(naqp.county(for: "XE")?.name, "Mexico")
        XCTAssertEqual(naqp.county(for: "CM")?.name, "Cuba")
        XCTAssertEqual(naqp.county(for: "4U1")?.name, "United Nations HQ",
                       "the checklist's '4U1/u' — '/' cannot be typed")
        XCTAssertEqual(naqp.county(for: "KP5")?.name, "Desecheo I.")
        XCTAssertEqual(naqp.county(for: "PJ7")?.name, "Sint Maarten")
        XCTAssertEqual(naqp.county(for: "FO")?.name, "Clipperton I.",
                       "the NA row of FO, not French Polynesia")
        XCTAssertEqual(naqp.county(for: "HK0")?.name, "San Andres & Providencia")
        XCTAssertEqual(naqp.county(for: "XF4")?.name, "Revillagigedo")
        XCTAssertEqual(naqp.county(for: "VP2E")?.name, "Anguilla")

        XCTAssertNil(naqp.county(for: "HI"),
                     "the Dominican Republic is shadowed by Hawaii — the caveat, pinned below")
        XCTAssertNil(naqp.county(for: "CO"),
                     "the sponsor's Cuba token is CM; CO stays Colorado")
        XCTAssertNil(naqp.county(for: "DL"), "non-NA countries are DX, never tokens")
    }

    // MARK: Shape

    func testPartyShape() {
        XCTAssertEqual(naqp.cabrilloContest, "NAQP-CW")
        XCTAssertEqual(naqp.homeState, "NA", "a pseudo-state: labels only, never a token")
        XCTAssertEqual(naqp.homeStates, ["NA"])
        XCTAssertEqual(naqp.allowedModeClasses, [.cw], "rule 7: CW only in CW parties")
        XCTAssertEqual(naqp.maxSimultaneousCounties, 1, "one location per exchange")
        XCTAssertEqual(naqp.dxStyle, .token)
        XCTAssertFalse(naqp.exchangeIncludesRST, "rule 10: name and location, no report")
        XCTAssertFalse(naqp.exchangeIncludesSerial)
        XCTAssertTrue(naqp.exchangeIncludesName)
        XCTAssertTrue(naqp.bonuses.isEmpty, "rule set has no bonuses at all")
        XCTAssertNil(naqp.scoreMultipliers, "QRP/Low are categories, not factors")
        XCTAssertNil(naqp.hubSpots, "qsopartyhub serves state parties")
        XCTAssertTrue(naqp.combines.isEmpty)
        XCTAssertFalse(naqp.isPartiallyVerified,
                       "fully verified from the sponsor's current document")
        XCTAssertFalse(naqp.outStateWorksHomeStationsOnly, "everyone works everyone")

        // No home-state machinery: nothing is excluded (your own state
        // counts), no alias (DC is its own multiplier), the standard 13
        // provinces.
        XCTAssertEqual(naqp.excludedStateTokens, ["NA"],
                       "the default — and NA is not a real token, so nothing is excluded")
        XCTAssertTrue(naqp.stateAliases.isEmpty)
        XCTAssertEqual(naqp.provinces, MultClass.canadianProvinces)

        // Both sides identical: county (the countries) + state + province,
        // counted again on each band, no caps, no granted mults.
        for rule in [naqp.multipliers.inState, naqp.multipliers.outState] {
            XCTAssertEqual(rule.classes, [.county, .state, .province])
            XCTAssertEqual(rule.countScope, .perBand)
            XCTAssertFalse(rule.homeStateCountsViaCounty)
            XCTAssertNil(rule.dxMultCap)
            XCTAssertNil(rule.maxScoredMultipliers)
            XCTAssertTrue(rule.granted.isEmpty)
        }
    }

    func testSixBandsAndNoWARC() {
        XCTAssertEqual(naqp.validBands, [.m160, .m80, .m40, .m20, .m15, .m10])
    }

    /// Rule 4's printed instants, with rule 5's exact endpoint ("the contest
    /// period ends at 05:59:59 UTC") as an exclusive 0600 end — both 2026
    /// runnings, the past January one included (Article 19: correct data).
    func testScheduleIsBothTwelveHourRunnings() throws {
        let windows = try XCTUnwrap(naqp.schedule)
        let iso = ISO8601DateFormatter()
        XCTAssertEqual(windows.count, 2)
        XCTAssertEqual(windows[0].start, iso.date(from: "2026-01-10T18:00:00Z"))
        XCTAssertEqual(windows[0].end, iso.date(from: "2026-01-11T06:00:00Z"))
        XCTAssertEqual(windows[1].start, iso.date(from: "2026-08-01T18:00:00Z"))
        XCTAssertEqual(windows[1].end, iso.date(from: "2026-08-02T06:00:00Z"))
    }

    // MARK: Exchange parsing

    func testEveryLocationShapeParses() {
        for token in ["XE", "4U1", "VP2E", "TX", "DC", "ON", "DX", "HI"] {
            let parsed = ExchangeParser.parse(token, party: naqp, role: .outOfState)
            guard case .success(let exchange) = parsed else {
                return XCTFail("\(token) should be a valid NAQP location")
            }
            XCTAssertEqual(exchange.locations, [token])
        }
    }

    /// No prefix guessing: `dx` is in neither side's classes, so a typo is
    /// rejected with suggestions instead of minting a phantom multiplier —
    /// unlike the token-open prefix parties.
    func testTyposAreRejectedNotGuessed() {
        for bad in ["TXX", "XW", "NA", "Q9"] {
            if case .success = ExchangeParser.parse(bad, party: naqp, role: .outOfState) {
                XCTFail("\(bad) should not validate")
            }
        }
    }

    func testOneLocationPerExchange() {
        guard case .failure(let error) = ExchangeParser.parse(
            "XE/6Y", party: naqp, role: .outOfState
        ) else { return XCTFail("two locations must not validate") }
        XCTAssertEqual(error, .tooManyCounties(2))
    }

    // MARK: Multipliers — again on each band

    /// "Multipliers count again on each band." The same value on a second
    /// band is a new multiplier; on the same band twice it is not — the case
    /// that passes under the wrong scope and fails under the right one.
    func testMultipliersCountAgainOnEachBand() {
        let s = ScoreEngine.score(log: log([
            qso(call: "XE2X", band: .m20, their: "XE"),
            qso(call: "XE2X", band: .m40, their: "XE"),
            qso(call: "XE1A", band: .m40, their: "XE"),
            qso(call: "K5OT", band: .m20, their: "TX"),
            qso(call: "W5KU", band: .m20, their: "TX"),
            qso(call: "VE3AT", band: .m20, their: "ON"),
            qso(call: "VE3AT", band: .m15, their: "ON"),
        ]), party: naqp)
        XCTAssertEqual(s.validQSOs, 7)
        XCTAssertEqual(s.qsoPoints, 7, "one point per valid contact")
        // XE on 20 and 40, TX on 20 (once), ON on 20 and 15.
        XCTAssertEqual(s.multiplierKeys.count, 5)
        XCTAssertEqual(s.total, 35)
    }

    /// Rule 11 lists DC alongside the 50 states — its own multiplier, never
    /// aliased to MD (the paper checklist omits it; the rules win).
    func testDCIsItsOwnMultiplier() {
        let s = ScoreEngine.score(log: log([
            qso(call: "W3DC", their: "DC"),
            qso(call: "W3MD", their: "MD"),
        ]), party: naqp)
        XCTAssertEqual(s.multiplierKeys.count, 2)
        XCTAssertEqual(s.workedValues(.state), ["DC", "MD"])
    }

    /// Nothing is excluded: a Texas entrant logging Texas earns the Texas
    /// multiplier — the opposite of every state party, and the reason the
    /// definition must not inherit an excluded home-state token.
    func testYourOwnStateCounts() {
        let s = ScoreEngine.score(log: log([qso(call: "K5OT", their: "TX")]), party: naqp)
        XCTAssertEqual(s.workedValues(.state), ["TX"])
        XCTAssertEqual(s.total, 1)
    }

    /// "Non-North American countries … do not count as multipliers but may be
    /// worked for QSO credit; these should be entered as DX" — the point
    /// pays, the multiplier never exists. Would fail if `dx` were a class.
    func testDXPaysAPointAndNeverAMultiplier() {
        let s = ScoreEngine.score(log: log([
            qso(call: "DL1ABC", band: .m20, their: "DX"),
            qso(call: "G4XYZ", band: .m20, their: "DX"),
            qso(call: "JA1NUT", band: .m40, their: "DX"),
        ]), party: naqp)
        XCTAssertEqual(s.validQSOs, 3)
        XCTAssertEqual(s.qsoPoints, 3)
        XCTAssertEqual(s.multiplierCount, 0)
        XCTAssertEqual(s.total, 0, "points with no multiplier score nothing yet")
    }

    /// **The caveat, pinned.** A received HI is credited as the state Hawaii
    /// — the Dominican Republic cannot be a distinct multiplier here, so
    /// working both on one band scores one multiplier where the sponsor
    /// counts two. Deliberate; scoreAffecting caveat in the definition.
    func testKnownGapHIIsHawaiiNeverTheDominicanRepublic() {
        let s = ScoreEngine.score(log: log([
            qso(call: "KH6LC", their: "HI"),
            qso(call: "HI3T", their: "HI"),
        ]), party: naqp)
        XCTAssertEqual(s.validQSOs, 2, "the second HI row is a different call, not a dupe")
        XCTAssertEqual(s.workedValues(.state), ["HI"])
        XCTAssertTrue(s.workedValues(.county).isEmpty)
        XCTAssertEqual(s.multiplierCount, 1, "the sponsor counts 2 — see the caveat")
    }

    // MARK: Modes and dupes

    /// Rule 7: "CW only in CW parties." A phone or digital row is invalid —
    /// no points, no multipliers — not merely worth zero.
    func testOnlyCWCounts() {
        let s = ScoreEngine.score(log: log([
            qso(call: "K5OT", mode: .cw, their: "TX"),
            qso(call: "W1AW", mode: .phone, their: "CT"),
            qso(call: "W9PA", mode: .digital, their: "IL"),
        ]), party: naqp)
        XCTAssertEqual(s.validQSOs, 1)
        XCTAssertEqual(s.invalidModeCount, 2)
        XCTAssertEqual(s.qsoPoints, 1)
        XCTAssertEqual(s.workedValues(.state), ["TX"])
    }

    /// Rule 12: "Stations may be worked once per band." One mode exists, so
    /// band+mode dupe scope is exactly per-band.
    func testDupesArePerBand() {
        let s = ScoreEngine.score(log: log([
            qso(call: "N2CU", band: .m20, their: "NY"),
            qso(call: "N2CU", band: .m20, their: "NY"),
            qso(call: "N2CU", band: .m40, their: "NY"),
        ]), party: naqp)
        XCTAssertEqual(s.validQSOs, 2)
        XCTAssertEqual(s.dupeCount, 1)
    }

    // MARK: The name exchange, end to end

    /// The party will not log a nameless contact: rule 12 counts only a
    /// complete copied exchange, and a nameless row is the blank ex1 column
    /// that blocks submission.
    func testLoggingRequiresTheReceivedName() {
        let doc = LogDocument()
        doc.updateStation(
            StationProfile(callsign: "KE5CW"),
            location: .outOfState(location: "TX"),
            partyID: "naqpcw",
            exchangeName: "Tom",
            undoManager: nil
        )
        let flow = EntryFlow(document: doc)
        let context = EntryFlow.Context(
            band: .m20, modeClass: .cw, rawMode: "CW",
            freqKHz: nil, radioConnected: false, cursor: .call,
            keying: KeyingSettings()
        )

        flow.entry.call = "N2CU"
        flow.entry.exchangeTyped = "NY"
        XCTAssertEqual(flow.logContact(context, undoManager: nil), .nothing,
                       "no received name, no contact")
        XCTAssertTrue(doc.log.qsos.isEmpty)

        flow.entry.nameRcvd = "BILL"
        guard case .logged(let rows, _) = flow.logContact(context, undoManager: nil) else {
            return XCTFail("a complete exchange logs")
        }
        XCTAssertEqual(rows.count, 1)
        XCTAssertEqual(rows[0].nameSent, "TOM", "the log's contest-long name, uppercased")
        XCTAssertEqual(rows[0].nameRcvd, "BILL")
        XCTAssertEqual(rows[0].theirLoc, "NY")
    }

    /// The sponsors' own line shape: `… KE5CW TOM TX N2CU BILL NY`.
    func testCabrilloCarriesTheNames() throws {
        let contest = log([qso(call: "N2CU", their: "NY")])
        let score = ScoreEngine.score(log: contest, party: naqp)
        let export = CabrilloExporter.export(log: contest, party: naqp, score: score)

        XCTAssertTrue(export.contains("CONTEST: NAQP-CW"), export)
        XCTAssertTrue(export.contains("LOCATION: TX"), "the entrant's own state")
        let line = try XCTUnwrap(export.split(separator: "\n").first { $0.hasPrefix("QSO:") })
        let fields = line.split(separator: " ").map(String.init)
        XCTAssertEqual(Array(fields.suffix(6)), ["KE5CW", "TOM", "TX", "N2CU", "BILL", "NY"])
    }

    // MARK: No home region — one location question, no hand-fixed header

    /// NAQP has no home state to be *inside* of. Rule 10 gives every North
    /// American entrant the same exchange shape, and the 46 country tokens
    /// riding in the county slot are peers of the states and provinces, not
    /// sub-regions of a host state. The Inside/Outside binary every state
    /// party needs is meaningless here, so this party turns it off.
    func testNAQPHasNoHomeRegion() throws {
        XCTAssertFalse(naqp.hasHomeRegion)
        let ssb = try XCTUnwrap(PartyCatalog.party(id: "naqpssb"))
        XCTAssertFalse(ssb.hasHomeRegion)

        let ksqp = try XCTUnwrap(PartyCatalog.party(id: "ksqp"))
        XCTAssertTrue(ksqp.hasHomeRegion, "every other party keeps the default")
    }

    /// So an entrant may claim any of the peer classes — their state, their
    /// province, their NA country, or the DX token rule 11 sends non-NA
    /// stations to.
    func testAnEntrantMayClaimAnyPeerLocation() throws {
        XCTAssertTrue(
            naqp.validEntrantTokens.isSuperset(of: ["TX", "ON", "XE", "VP9", "8P", "DX"]),
            "states, provinces, countries and DX are one flat list here"
        )

        let ksqp = try XCTUnwrap(PartyCatalog.party(id: "ksqp"))
        XCTAssertEqual(ksqp.validEntrantTokens, ksqp.validOutStateTokens,
                       "a party with a home region is untouched")
        XCTAssertFalse(ksqp.validEntrantTokens.contains("MRN"),
                       "a Kansas county is not something a Kansas entrant types here")
    }

    /// The jank this replaces: an entrant in Mexico picked "Inside", and the
    /// header exported as the pseudo-state `NA` — the app told them to
    /// hand-fix it before submitting. Whatever they send is what ships.
    func testTheEntrantsOwnTokenIsTheCabrilloLocation() {
        var contest = log([qso(call: "N2CU", my: "XE", their: "NY")])
        contest.myLocation = .outOfState(location: "XE")
        let export = CabrilloExporter.export(log: contest, party: naqp, score: .init())
        XCTAssertTrue(export.contains("LOCATION: XE"), export)
    }

    /// And a log written the old way — the country stored as an in-state
    /// county — exports the same header without being opened in setup again.
    func testALegacyInsideLogStillExportsItsCountry() {
        var contest = log([qso(call: "N2CU", my: "XE", their: "NY")])
        contest.myLocation = .inState(counties: ["XE"])
        let export = CabrilloExporter.export(log: contest, party: naqp, score: .init())
        XCTAssertTrue(export.contains("LOCATION: XE"), "not the pseudo-state: \(export)")
        XCTAssertFalse(export.contains("LOCATION: NA"))
    }

    /// What makes collapsing the two cases safe: rule 11 has no asymmetry,
    /// so both mult rules are identical and the classification cannot move a
    /// score either way.
    func testTheClassificationCannotMoveTheScore() {
        let rows = [
            qso(call: "N2CU", their: "NY"),
            qso(call: "W0BH", band: .m40, their: "KS"),
        ]
        var inside = log(rows)
        inside.myLocation = .inState(counties: ["XE"])
        var outside = log(rows)
        outside.myLocation = .outOfState(location: "XE")

        let a = ScoreEngine.score(log: inside, party: naqp)
        let b = ScoreEngine.score(log: outside, party: naqp)
        XCTAssertEqual(a.total, b.total)
        XCTAssertEqual(a.multiplierCount, b.multiplierCount)
        XCTAssertEqual(a.validQSOs, b.validQSOs)
    }

    /// Widening what an entrant may *claim* must not widen what they may
    /// *receive*: the country tokens stay county-class multipliers, taken by
    /// the county branch of the parser exactly as before.
    func testReceivedCountryTokensAreStillCountyClass() {
        guard case .success(let parsed) =
                ExchangeParser.parse("XE", party: naqp, role: .outOfState) else {
            return XCTFail("XE must still parse")
        }
        XCTAssertTrue(parsed.isInStateCounties, "the county branch, not the out-token branch")
        XCTAssertEqual(parsed.locations, ["XE"])
    }

    // MARK: Entry classifications (rules 5 and 6)

    /// Rule 5B — Single Operator Assisted: one operator, spotting allowed —
    /// is `SINGLE-OP` + `ASSISTED`, the pair the operator's own January 2026
    /// entry carried. Rule 6A rides along: QRP is a competitive category,
    /// not a score factor (`testPartyShape` pins the nil `scoreMultipliers`).
    func testCabrilloDeclaresASingleOpAssistedQRPEntry() {
        var contest = log([qso(call: "N2CU", their: "NY")])
        contest.station.categoryOperator = .singleOp
        contest.station.categoryAssisted = .assisted
        contest.station.categoryPower = .qrp
        let score = ScoreEngine.score(log: contest, party: naqp)
        let export = CabrilloExporter.export(log: contest, party: naqp, score: score)
        let lines = export.components(separatedBy: "\n")

        XCTAssertTrue(lines.contains("CATEGORY-OPERATOR: SINGLE-OP"))
        XCTAssertTrue(lines.contains("CATEGORY-ASSISTED: ASSISTED"))
        XCTAssertTrue(lines.contains("CATEGORY-POWER: QRP"))
    }

    /// Rule 5C — Multioperator Two-Transmitter: `MULTI-OP`, `TWO`, the crew
    /// in `OPERATORS:`, spotting allowed (5C(ii)), and 5C(vii)'s single
    /// shared name in every sent exchange — the log-wide `exchangeName`
    /// mechanism, visible in each QSO line's sent-name column.
    func testCabrilloDeclaresAMultiTwoEntry() {
        var contest = log([
            qso(call: "N2CU", their: "NY"),
            qso(call: "W0BH", band: .m40, their: "KS"),
        ])
        contest.station.categoryOperator = .multiOp
        contest.station.categoryAssisted = .assisted
        contest.station.categoryTransmitter = .two
        contest.station.operators = "KE5CW W5XYZ"
        let score = ScoreEngine.score(log: contest, party: naqp)
        let export = CabrilloExporter.export(log: contest, party: naqp, score: score)
        let lines = export.components(separatedBy: "\n")

        XCTAssertTrue(lines.contains("CATEGORY-OPERATOR: MULTI-OP"))
        XCTAssertTrue(lines.contains("CATEGORY-ASSISTED: ASSISTED"))
        XCTAssertTrue(lines.contains("CATEGORY-TRANSMITTER: TWO"))
        XCTAssertTrue(lines.contains("OPERATORS: KE5CW W5XYZ"))
        let qsoLines = lines.filter { $0.hasPrefix("QSO:") }
        XCTAssertEqual(qsoLines.count, 2)
        for line in qsoLines {
            XCTAssertTrue(line.contains(" TOM "),
                          "one name for the whole contest, rule 5C(vii): \(line)")
        }
    }

    func testDefaultMessagesSendNameThenLocation() {
        let sets = MessageSets.defaults(for: naqp)
        XCTAssertTrue(sets.searchPounce.contains("{NAME} {EXCH}"), "\(sets.searchPounce)")
        XCTAssertFalse(sets.run.contains { $0.contains("{RST}") },
                       "the exchange carries no report")
    }

    // MARK: Not a Challenge contest

    /// KE5CW, 2026-07-27: "they do not count in the state qso party
    /// challenge." The Challenge's own approved list is the mechanism — NAQP
    /// is not on it, so a logged NAQP shows under "not approved" and
    /// contributes nothing.
    func testNAQPIsNotAChallengeContest() throws {
        let calendar = try XCTUnwrap(ChallengeCalendar.loadBundled())
        XCTAssertNil(calendar.contest(partyID: "naqpcw"))
        XCTAssertNil(calendar.contest(named: "North American QSO Party, CW"))

        var naqpLog = log([
            qso(call: "N2CU", their: "NY"),
            qso(call: "XE2X", their: "XE"),
        ])
        naqpLog.station.callsign = "KE5CW"
        var ksqpLog = ContestLog(partyID: "ksqp")
        ksqpLog.station.callsign = "KE5CW"
        ksqpLog.myLocation = .outOfState(location: "TX")
        ksqpLog.qsos = (0..<10).map { i in
            QSO(timestampUTC: Date(timeIntervalSince1970: 1_787_000_000 + Double(i) * 60),
                call: "W\(i)KS", band: .m20, modeClass: .cw, rawMode: "CW",
                rstSent: "599", rstRcvd: "599", myLoc: "TX", theirLoc: "ALL")
        }

        let records = [naqpLog, ksqpLog].compactMap {
            ContestRecord.make(
                from: $0,
                snapshot: ScoreSnapshot.countsOnly(log: $0),
                updatedAt: Date(timeIntervalSince1970: 1_785_607_200),
                sourceFileName: nil
            )
        }
        let standing = ChallengeStanding.compute(
            records: records, calendar: calendar, year: 2026,
            partyNames: ["naqpcw": "North American QSO Party, CW"]
        )

        XCTAssertEqual(standing.notApproved.map(\.partyID), ["naqpcw"],
                       "shown, never silently dropped, contributing nothing")
        XCTAssertEqual(standing.qsoSum, 10, "only the state party's QSOs sum")
        XCTAssertEqual(standing.multiplier, 1)
        XCTAssertEqual(standing.points, 10)
    }

    /// It still appears in the dashboard's upcoming list — as an operable
    /// contest with sponsor dates, labeled not-approved — because a contest
    /// you can operate is not the same thing as a contest that scores
    /// Challenge points.
    func testNAQPIsUpcomingButNotApproved() throws {
        let calendar = try XCTUnwrap(ChallengeCalendar.loadBundled())
        let upcoming = UpcomingContests.upcoming(
            now: Date(timeIntervalSince1970: 1_785_000_000),  // 2026-07-25
            parties: PartyCatalog.loadBundled(),
            calendar: calendar,
            records: []
        )
        let row = try XCTUnwrap(upcoming.first { $0.partyID == "naqpcw" })
        XCTAssertFalse(row.isApproved)
        XCTAssertEqual(row.dateSource, .partyDefinition)
        XCTAssertEqual(row.nextWindow.start, ISO8601DateFormatter().date(from: "2026-08-01T18:00:00Z"))
    }
}
