import XCTest
@testable import QSOPartyLogger

/// Parsing the shapes the real MASTER.SCP has (observed 2026-08-04: an
/// `!!Order,1,1` directive, `#` comments carrying `# Release 2026.07.31`,
/// then one uppercase call per CRLF line), and the match semantics the
/// strip shows. Pure value code — no I/O anywhere in this suite.
final class SCPDatabaseTests: XCTestCase {

    /// The live file's exact head, shrunk to five calls.
    private let realShape = "!!Order,1,1\r\n#\r\n# Super Check Partial\r\n"
        + "# Release 2026.07.31\r\n# Generated by bb-scp\r\n#\r\n"
        + "2E0AOZ\r\nK5C\r\nN5KO\r\nN5KW\r\nW5NK\r\n"

    // MARK: Parsing

    func testParsesTheRealFileShape() throws {
        let db = try XCTUnwrap(SCPDatabase.parse(data: Data(realShape.utf8)))
        XCTAssertEqual(db.calls, ["2E0AOZ", "K5C", "N5KO", "N5KW", "W5NK"])
        XCTAssertEqual(db.recordCount, 5)
        XCTAssertEqual(db.release, "2026.07.31")
    }

    /// The directive and comment lines must not survive as "calls".
    func testDirectiveAndCommentsAreNotCalls() throws {
        let db = try XCTUnwrap(SCPDatabase.parse(data: Data(realShape.utf8)))
        XCTAssertFalse(db.calls.contains { $0.hasPrefix("#") || $0.hasPrefix("!") })
    }

    func testLowercaseAndDuplicatesAndBlanksNormalize() throws {
        let text = "n5ko\nN5KO\n\n  W5NK  \nk5c\n"
        let db = try XCTUnwrap(SCPDatabase.parse(data: Data(text.utf8)))
        XCTAssertEqual(db.calls, ["K5C", "N5KO", "W5NK"])
        XCTAssertNil(db.release)
    }

    /// Tokens that cannot be callsigns — wrong charset or shorter than three
    /// — are dropped rather than offered.
    func testGarbageTokensAreDropped() throws {
        let text = "N5KO\nAB\nBAD CALL\nN0??\nW5NK/M\n"
        let db = try XCTUnwrap(SCPDatabase.parse(data: Data(text.utf8)))
        XCTAssertEqual(db.calls, ["N5KO", "W5NK/M"])
    }

    /// The site could serve Latin-1 bytes some day; they decode rather than
    /// vanish. (0xD1 is Ñ in isoLatin1 and invalid alone as UTF-8 — the Ñ
    /// then fails the charset rule, and the file still parses.)
    func testISOLatin1BytesStillParse() throws {
        var bytes = Data("N5KO\nW5N".utf8)
        bytes.append(0xD1)
        bytes.append(Data("\nK5C\n".utf8))
        let db = try XCTUnwrap(SCPDatabase.parse(data: bytes))
        XCTAssertEqual(db.calls, ["K5C", "N5KO"])
    }

    // MARK: Matching

    private var db: SCPDatabase {
        // NB: KE5CW does *not* contain "K5C" (the E splits it) — it is here
        // to prove containment is literal, not fuzzy.
        SCPDatabase(
            calls: ["K5C", "K5CW", "KE5CW", "N5KO", "N5KW", "W5NK", "WK5CT"],
            release: nil
        )
    }

    /// Exact call first, then calls starting with the fragment, then calls
    /// merely containing it — alphabetical inside each tier.
    func testTiersExactThenPrefixThenContainment() {
        XCTAssertEqual(
            db.matches(for: "K5C", limit: 10).calls,
            ["K5C", "K5CW", "WK5CT"]
        )
        XCTAssertEqual(
            db.matches(for: "N5K", limit: 10).calls,
            ["N5KO", "N5KW"]
        )
    }

    func testMatchIsCaseAndWhitespaceBlind() {
        XCTAssertEqual(db.matches(for: " k5c ", limit: 10).calls.first, "K5C")
    }

    /// Two characters match thousands of calls and mean nothing yet.
    func testFragmentsBelowTheFloorMatchNothing() {
        XCTAssertEqual(db.matches(for: "K5", limit: 10), .none)
        XCTAssertEqual(db.matches(for: "", limit: 10), .none)
        XCTAssertEqual(SCPDatabase.minimumFragmentLength, 3)
    }

    /// The cap trims the list but the total stays truthful — it is what
    /// lets the strip say "+N more" honestly.
    func testLimitCapsCallsButNotTotal() {
        let capped = db.matches(for: "K5C", limit: 2)
        XCTAssertEqual(capped.calls, ["K5C", "K5CW"], "WK5CT is past the cap")
        XCTAssertEqual(capped.total, 3)
    }

    func testNoMatchIsEmptyNotAnError() {
        XCTAssertEqual(db.matches(for: "ZZZ9", limit: 10), .none)
    }

    /// The floor an installed file must clear — an error page or truncated
    /// stub will not produce a thousand tokens that scan as callsigns.
    func testMinimumRecordsFloor() {
        XCTAssertEqual(SCPDatabase.minimumRecords, 1000)
    }
}
