import Foundation

/// Where a party's N1MM call history file lives in the community listing at
/// n1mmwp.hamdocs.com — the per-contest lookup files the N1MM ecosystem
/// maintains (mostly VE2FK), holding what each station is expected to send.
///
/// Only the **stable prefix** is bundled, never a URL: every uploaded revision
/// gets its own page slug (`qsop_al-2026-002-txt`), so a bundled link dies the
/// week the maintainer refreshes the file — which is the week before the
/// contest, the only week that matters. Discovery searches the listing for the
/// prefix at use time and takes the newest matching filename.
///
/// The data these files carry is a **hint, never a rule** (constitution
/// Article 1): nothing from them reaches `ScoreEngine`, and no value is
/// offered to the operator without surviving the party's own
/// `ExchangeParser` first.
///
/// Generated by `docs/research/gen_callhistory.py`; provenance in
/// `docs/research/n1mm_callhistory.md`.
struct CallHistorySource: Codable, Equatable, Sendable {

    /// Filename stem the listing is searched for (`QSOP_AL`, `NAQPCW`,
    /// `QSOP_IN7QPNE_DE` for the five parties the shared May file serves).
    let filePrefix: String

    /// Comment the file itself must carry (`QSOPARTY AL`, `NAQPCW`) before a
    /// download is installed — the files declare who they serve, and a
    /// download that does not declare this party is discarded. `nil` skips
    /// the check (user-supplied definitions may not know the token).
    let token: String?

    /// Whether `filename` is a revision of this party's file: the prefix
    /// followed by a separator, case-insensitively. The separator is what
    /// stops Nebraska's `QSOP_NE` claiming New England's `QSOP_NEWE-…`, and
    /// Indiana's `QSOP_IN` claiming the combined `QSOP_IN7QPNE_DE-…`.
    func claims(fileNamed filename: String) -> Bool {
        let name = filename.uppercased()
        let prefix = filePrefix.uppercased()
        for separator in ["-", "_", "."] where name.hasPrefix(prefix + separator) {
            return true
        }
        return false
    }

    /// Whether a downloaded file's comments declare this party. `tokens` is
    /// the file's normalized comment set (`CallHistoryFile.Parsed.tokens`).
    /// True when no token is configured — nothing to check against.
    func isDeclared(inCommentTokens tokens: Set<String>) -> Bool {
        guard let token else { return true }
        return tokens.contains(Self.normalized(token))
    }

    /// Uppercased with all whitespace removed. Whitespace-blind because the
    /// files are hand-maintained and drift: QSOP_OH-2025-003.txt writes
    /// `# QSO PARTY OH` where every sibling writes `# QSOPARTY XX`.
    static func normalized(_ text: String) -> String {
        text.uppercased().filter { !$0.isWhitespace }
    }
}
