import Foundation

/// Where a party's N1MM call history file lives in the community listing at
/// n1mmwp.hamdocs.com — the per-contest lookup files the N1MM ecosystem
/// maintains (mostly VE2FK), holding what each station is expected to send.
///
/// Only the **stable prefix** is bundled, never a URL: every uploaded revision
/// gets its own page slug (`qsop_al-2026-002-txt`), so a bundled link dies the
/// week the maintainer refreshes the file — which is the week before the
/// contest, the only week that matters. Discovery searches the listing for the
/// prefix at use time and takes the newest matching filename.
///
/// The data these files carry is a **hint, never a rule** (constitution
/// Article 1): nothing from them reaches `ScoreEngine`, and no value is
/// offered to the operator without surviving the party's own
/// `ExchangeParser` first.
///
/// Generated by `docs/research/gen_callhistory.py`; provenance in
/// `docs/research/n1mm_callhistory.md`.
struct CallHistorySource: Codable, Equatable, Sendable {

    /// Where a party's prefill data is discovered. The default — absent from
    /// every JSON written before the field existed — is the N1MM community
    /// listing. `w2ljRosterPage` is the Skeeter Hunt's arrangement: no N1MM
    /// file exists (full inventory, 2026-08-04), and the roster is a Google
    /// Sheet whose document id changes every season, so discovery starts
    /// from the sponsor page that links it — the same stable-root role the
    /// N1MM listing URL plays for everyone else.
    enum Kind: String, Codable, Sendable {
        case n1mm
        case w2ljRosterPage
        /// The ARS Flight of the Bumblebees arrangement: the sponsor's
        /// self-serve number report is one HTML table at a stable URL
        /// (`pageURL`), so there is no discovery hop at all — fetch, parse,
        /// convert. Live data like the roster kind above: numbers issue
        /// until the event and the table resets for each running, so the
        /// daily clock re-downloads with no unchanged-revision short circuit.
        case arsFobbRoster
    }

    var kind: Kind { kindRaw ?? .n1mm }
    private let kindRaw: Kind?

    /// The sponsor page a roster kind discovers from. Bundled in the JSON
    /// rather than hardcoded so a user file can override it mid-season
    /// (Article 21). `nil` for the N1MM kind, whose listing URL is shared.
    let pageURL: String?

    /// Filename stem the listing is searched for (`QSOP_AL`, `NAQPCW`,
    /// `QSOP_IN7QPNE_DE` for the five parties the shared May file serves).
    /// A roster kind uses it only as the cache's self-description.
    let filePrefix: String

    /// Comment the file itself must carry (`QSOPARTY AL`, `NAQPCW`) before a
    /// download is installed — the files declare who they serve, and a
    /// download that does not declare this party is discarded. `nil` skips
    /// the check (user-supplied definitions may not know the token). A
    /// roster kind's converter writes the token into the file it builds, so
    /// the same gate proves the conversion produced what it claims.
    let token: String?

    init(filePrefix: String, token: String?, kind: Kind = .n1mm, pageURL: String? = nil) {
        self.filePrefix = filePrefix
        self.token = token
        self.kindRaw = kind == .n1mm ? nil : kind
        self.pageURL = pageURL
    }

    private enum CodingKeys: String, CodingKey {
        case filePrefix, token, pageURL
        case kindRaw = "kind"
    }

    /// Whether `filename` is a revision of this party's file: the prefix
    /// followed by a separator, case-insensitively. The separator is what
    /// stops Nebraska's `QSOP_NE` claiming New England's `QSOP_NEWE-…`, and
    /// Indiana's `QSOP_IN` claiming the combined `QSOP_IN7QPNE_DE-…`.
    func claims(fileNamed filename: String) -> Bool {
        let name = filename.uppercased()
        let prefix = filePrefix.uppercased()
        for separator in ["-", "_", "."] where name.hasPrefix(prefix + separator) {
            return true
        }
        return false
    }

    /// Whether a downloaded file's comments declare this party. `tokens` is
    /// the file's normalized comment set (`CallHistoryFile.Parsed.tokens`).
    /// True when no token is configured — nothing to check against.
    func isDeclared(inCommentTokens tokens: Set<String>) -> Bool {
        guard let token else { return true }
        return tokens.contains(Self.normalized(token))
    }

    /// Uppercased with all whitespace removed. Whitespace-blind because the
    /// files are hand-maintained and drift: QSOP_OH-2025-003.txt writes
    /// `# QSO PARTY OH` where every sibling writes `# QSOPARTY XX`.
    static func normalized(_ text: String) -> String {
        text.uppercased().filter { !$0.isWhitespace }
    }
}
