import Foundation

/// Where a party's spots live on qsopartyhub.com — the volunteer-run board
/// several sponsors point their operators at for self-spotting.
///
/// Unlike a DX cluster spot, a hub spot carries the **county**, which is the
/// multiplier the whole party is scored on. That single field is the reason
/// this source exists; its volume is nowhere near a cluster's.
///
/// `tableURL` is resolved from the iframe each party's own `-spots.php` page
/// embeds, never from the party id. `caqp-table.php` exists and returns a
/// well-formed but permanently empty table while the California page actually
/// embeds `qp-table.php` (a redirect) — so a prefix guess produces a poller
/// that runs forever, never errors, and shows nothing.
///
/// Generated by `docs/research/gen_hub_map.py`; provenance in
/// `docs/research/qsopartyhub.md`.
struct HubSpotSource: Codable, Equatable, Sendable {

    /// Page holding the spot table this app polls.
    let tableURL: String

    /// Page holding the self-spot form this app posts to.
    let postURL: String

    /// Hub county token → this party's official abbreviation, for the cases
    /// where the hub's own list disagrees with the sponsor's. Only Illinois
    /// needs one today (the hub spells Pulaski `PULS`, the official list
    /// `PULA`). Inbound spots are translated through this map; a self-spot has
    /// to translate back, since the hub's form accepts only its own token.
    var countyAliases: [String: String] { countyAliasesRaw ?? [:] }
    private let countyAliasesRaw: [String: String]?

    /// This party's abbreviation → the token the hub's form expects.
    var reverseCountyAliases: [String: String] {
        Dictionary(uniqueKeysWithValues: countyAliases.map { ($0.value, $0.key) })
    }

    private enum CodingKeys: String, CodingKey {
        case tableURL, postURL
        case countyAliasesRaw = "countyAliases"
    }
}
